name: Build Dev Image

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build-dev-image.yml"
      - "dev-docker/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./dev-docker
          push: true
          platforms: linux/arm64
          tags: |
            dizy/nyu-multicore-lab-1-dev:latest
            dizy/nyu-multicore-lab-1-dev:${{ github.sha }}
